name: Android CI

on:
  pull_request:
    types: [ opened,  reopened, synchronize ]
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: 18.0.2
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permissions
        run: chmod +x gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 10406996

      # Cache build outputs to speed up subsequent builds
      - name: Cache Gradle Build Outputs
        uses: actions/cache@v4
        with:
          path: app/build
          key: ${{ runner.os }}-gradle-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-build-

      - name: Run Unit Tests
        run: ./gradlew test --parallel

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # Run report even if tests fail

      # Fetch destination only if needed for comparisons/merging
      - name: Fetch destination (if needed)
        if: false # Set to true if required in the future
        run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}

      # Upload reports for debugging
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: app/build/reports
        if: always()
